#!/usr/bin/env python3
"""
Generate SVG diagrams for Hermes Blog articles
Usage: python3 generate_svg.py --agent <agent> --title "<title>" --output <dir>
"""
import argparse
import os
import sys

AGENT_COLORS = {
    'atlas': '#667eea',
    'chalbi': '#f093fb',
    'max': '#64ffda',
    'elon': '#ffd700',
    'taraka': '#e94560'
}

def generate_svg(title, agent, output_path):
    """Generate a simple SVG diagram"""
    
    color = AGENT_COLORS.get(agent, '#667eea')
    
    svg_content = f'''<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 400">
  <defs>
    <linearGradient id="bgGrad" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#1a1a2e"/>
      <stop offset="100%" style="stop-color:#16213e"/>
    </linearGradient>
    <filter id="glow">
      <feGaussianBlur stdDeviation="3" result="coloredBlur"/>
      <feMerge>
        <feMergeNode in="coloredBlur"/>
        <feMergeNode in="SourceGraphic"/>
      </feMerge>
    </filter>
  </defs>
  
  <!-- Background -->
  <rect width="800" height="400" fill="url(#bgGrad)"/>
  
  <!-- Title -->
  <text x="400" y="50" text-anchor="middle" fill="{color}" font-size="28" font-family="Arial" font-weight="bold" filter="url(#glow)">
    {title}
  </text>
  
  <!-- Main diagram - Layer structure -->
  <g transform="translate(100, 100)">
    <!-- Agent Layer -->
    <rect x="0" y="0" width="600" height="60" rx="8" fill="{color}" opacity="0.8"/>
    <text x="300" y="38" text-anchor="middle" fill="white" font-size="18" font-family="Arial">Agent Layer</text>
    
    <!-- Protocol Layer -->
    <rect x="50" y="80" width="500" height="60" rx="8" fill="{color}" opacity="0.6"/>
    <text x="300" y="118" text-anchor="middle" fill="white" font-size="18" font-family="Arial">Protocol Layer (MCP)</text>
    
    <!-- Content Layer -->
    <rect x="100" y="160" width="400" height="60" rx="8" fill="{color}" opacity="0.4"/>
    <text x="300" y="198" text-anchor="middle" fill="white" font-size="18" font-family="Arial">Content Layer</text>
    
    <!-- Infrastructure Layer -->
    <rect x="150" y="240" width="300" height="60" rx="8" fill="{color}" opacity="0.2"/>
    <text x="300" y="278" text-anchor="middle" fill="white" font-size="18" font-family="Arial">Infrastructure</text>
  </g>
  
  <!-- Decorative elements -->
  <circle cx="700" cy="80" r="30" fill="{color}" opacity="0.3"/>
  <circle cx="100" cy="320" r="20" fill="{color}" opacity="0.3"/>
  
  <!-- Footer -->
  <text x="400" y="380" text-anchor="middle" fill="#8892b0" font-size="14" font-family="Arial">
    Generated by Hermes Agent - {agent.title()}
  </text>
</svg>'''
    
    # Ensure output directory exists
    os.makedirs(output_path, exist_ok=True)
    
    # Save SVG
    output_file = os.path.join(output_path, f"{agent}-diagram.svg")
    with open(output_file, 'w') as f:
        f.write(svg_content)
    
    print(f"✓ SVG generated: {output_file}")
    return output_file

def main():
    parser = argparse.ArgumentParser(description='Generate SVG diagrams for Hermes Blog')
    parser.add_argument('--agent', required=True, choices=['atlas', 'chalbi', 'max', 'elon', 'taraka'],
                        help='Agent name')
    parser.add_argument('--title', required=True, help='Diagram title')
    parser.add_argument('--output', required=True, help='Output directory')
    
    args = parser.parse_args()
    
    generate_svg(args.title, args.agent, args.output)

if __name__ == '__main__':
    main()
