#!/usr/bin/env python3
"""
Kanban Setup Script untuk Hermes Agent
Inisialisasi board kanban, config, dan demo tasks
"""

import sqlite3
import os
import json
from datetime import datetime
from pathlib import Path

# Paths
HERMES_HOME = Path.home() / ".hermes"
KANBAN_DB = HERMES_HOME / "kanban.db"
CONFIG_FILE = HERMES_HOME / "config.yaml"
SCRIPT_DIR = Path(__file__).parent

def init_database():
    """Initialize Kanban SQLite database"""
    HERMES_HOME.mkdir(parents=True, exist_ok=True)
    
    conn = sqlite3.connect(KANBAN_DB)
    c = conn.cursor()
    
    # Create boards table
    c.execute('''
        CREATE TABLE IF NOT EXISTS boards (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT UNIQUE NOT NULL,
            description TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            status TEXT DEFAULT 'active'
        )
    ''')
    
    # Create tasks table
    c.execute('''
        CREATE TABLE IF NOT EXISTS tasks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            board_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            description TEXT,
            status TEXT DEFAULT 'todo',
            priority TEXT DEFAULT 'medium',
            assignee TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            completed_at TIMESTAMP,
            blocked_reason TEXT,
            parent_task_id INTEGER,
            FOREIGN KEY (board_id) REFERENCES boards(id),
            FOREIGN KEY (parent_task_id) REFERENCES tasks(id)
        )
    ''')
    
    # Create comments table
    c.execute('''
        CREATE TABLE IF NOT EXISTS comments (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            task_id INTEGER NOT NULL,
            author TEXT,
            content TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (task_id) REFERENCES tasks(id)
        )
    ''')
    
    # Create indexes
    c.execute('CREATE INDEX IF NOT EXISTS idx_tasks_board ON tasks(board_id)')
    c.execute('CREATE INDEX IF NOT EXISTS idx_tasks_status ON tasks(status)')
    c.execute('CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks(assignee)')
    
    conn.commit()
    conn.close()
    print(f"✓ Database initialized: {KANBAN_DB}")

def add_demo_board():
    """Add a demo board for testing"""
    conn = sqlite3.connect(KANBAN_DB)
    c = conn.cursor()
    
    # Check if demo board exists
    c.execute("SELECT id FROM boards WHERE name = ?", ("Demo-Proyek",))
    if c.fetchone():
        print("✓ Demo board already exists")
        conn.close()
        return
    
    # Insert demo board
    c.execute(
        "INSERT INTO boards (name, description) VALUES (?, ?)",
        ("Demo-Proyek", "Board demo untuk testing Kanban")
    )
    board_id = c.lastrowid
    
    # Insert demo tasks
    demo_tasks = [
        ("Tulis Bab 1", "Mulai menulis chapter pertama", "todo", "high", "atlas", None),
        ("Review Bab 1", "Review dan revisi chapter 1", "todo", "medium", None, None),
        ("Generate Ilustrasi", "Buat ilustrasi SVG dan PNG", "in-progress", "high", "zetta", None),
        ("Upload ke GitHub", "Commit dan push changes", "todo", "medium", "max", None),
        ("Deploy ke FTP", "Upload files ke server", "blocked", "low", None, "Menunggu review"),
    ]
    
    for task in demo_tasks:
        title, desc, status, priority, assignee, blocked_reason = task
        
        c.execute(
            """INSERT INTO tasks 
               (board_id, title, description, status, priority, assignee, blocked_reason)
               VALUES (?, ?, ?, ?, ?, ?, ?)""",
            (board_id, title, desc, status, priority, assignee, blocked_reason)
        )
    
    conn.commit()
    conn.close()
    print("✓ Demo board dan tasks created")

def update_config():
    """Update Hermes config.yaml with kanban settings"""
    if not CONFIG_FILE.exists():
        # Create new config
        config_content = """# Hermes Agent Configuration
# Generated by kanban-setup.py

display:
  interface: tui
  skin: default

delegation:
  model: stealth/ox-alpha
  provider: openrouter
  max_concurrent_children: 3

kanban:
  enabled: true
  dispatch_in_gateway: true
  failure_limit: 2
"""
        CONFIG_FILE.write_text(config_content)
        print(f"✓ Config created: {CONFIG_FILE}")
    else:
        # Append kanban config if not exists
        content = CONFIG_FILE.read_text()
        if "kanban:" not in content:
            with open(CONFIG_FILE, 'a') as f:
                f.write("""
# Kanban Configuration
kanban:
  enabled: true
  dispatch_in_gateway: true
  failure_limit: 2
""")
            print(f"✓ Kanban config added to: {CONFIG_FILE}")
        else:
            print("✓ Kanban config already exists")

def show_menu():
    """Show interactive menu"""
    print("\n" + "="*50)
    print("📋 HERMES KANBAN SETUP")
    print("="*50)
    print("\n1. Init Database")
    print("2. Add Demo Board")
    print("3. Update Config")
    print("4. Show All Tasks")
    print("5. Run Full Setup")
    print("6. Exit")
    print("\n" + "="*50)

def show_tasks():
    """Display all tasks"""
    conn = sqlite3.connect(KANBAN_DB)
    c = conn.cursor()
    
    c.execute("""
        SELECT b.name, t.id, t.title, t.status, t.priority, t.assignee
        FROM tasks t
        JOIN boards b ON t.board_id = b.id
        ORDER BY b.name, t.status, t.priority
    """)
    
    tasks = c.fetchall()
    conn.close()
    
    if not tasks:
        print("No tasks found")
        return
    
    print("\n📊 KANBAN TASKS")
    print("-"*50)
    
    current_board = None
    for board_name, task_id, title, status, priority, assignee in tasks:
        if board_name != current_board:
            print(f"\n📁 {board_name}")
            current_board = board_name
        
        status_emoji = {
            'todo': '⏳',
            'in-progress': '🔄',
            'done': '✅',
            'blocked': '🚫'
        }.get(status, '❓')
        
        priority_emoji = {
            'high': '🔴',
            'medium': '🟡',
            'low': '🟢'
        }.get(priority, '⚪')
        
        assignee_str = f"@{assignee}" if assignee else "Unassigned"
        print(f"  [{task_id}] {status_emoji} {priority_emoji} {title[:40]:40s} {assignee_str}")
    
    print()

def main():
    """Main setup flow"""
    print("\n🚀 Hermes Kanban Setup")
    print("="*50)
    
    # Step 1: Init database
    print("\n[1/3] Initializing database...")
    init_database()
    
    # Step 2: Add demo data
    print("\n[2/3] Adding demo board and tasks...")
    add_demo_board()
    
    # Step 3: Update config
    print("\n[3/3] Updating config...")
    update_config()
    
    # Show results
    print("\n" + "="*50)
    print("✅ SETUP COMPLETE!")
    print("="*50)
    show_tasks()
    
    print("\n📖 Usage:")
    print("  hermes kanban list          - Show all boards")
    print("  hermes kanban show --id <ID> - Show board details")
    print("  hermes kanban create --task 'Title' --board <ID>")
    print("  hermes kanban complete --task-id <ID>")
    print("  hermes kanban block --task-id <ID> --reason '...')")
    print("\n💡 Tips:")
    print("  - Use 'todo', 'in-progress', 'done', 'blocked' as status")
    print("  - Priorities: high, medium, low")
    print("  - Assignees should match Hermes profile names")

if __name__ == "__main__":
    main()
